export const data = [
    {
        status: "default",
        headerDefault: "Сказочное заморское явство",
        headerHover: "Котэ не одобряет?",
        name: "Нямушка",
        type: "с фуа-гра",
        count: "10 порций",
        gift: "мышь в подарок",
        text: "",
        weight: 0.5,
        footerDefault: "<p>Чего сидишь? Порадуй котэ, <span>купи</span>.</p>",
        footerSelected: "Печень утки разварная с артишоками.",
        footerDisabled: "Печалька, с фуа-гра закончился.",
    },
    {
        status: "selected",
        headerDefault: "Сказочное заморское явство",
        headerHover: "Котэ не одобряет?",
        name: "Нямушка",
        type: "с рыбой",
        count: "40 порций",
        gift: "2 мыши в подарок",
        text: "",
        weight: 2,
        footerDefault: "<p>Чего сидишь? Порадуй котэ, <span>купи</span>.</p>",
        footerSelected: "Головы щучьи с чесноком да свежайшая сёмгушка.",
        footerDisabled: "Печалька, с рыбой закончился.",
    },
    {
        status: "disabled",
        headerDefault: "Сказочное заморское явство",
        headerHover: "Котэ не одобряет?",
        name: "Нямушка",
        type: "с курой",
        count: "100 порций",
        gift: "5 мышей в подарок",
        text: "заказчик доволен",
        weight: 5,
        footerDefault: "<p>Чего сидишь? Порадуй котэ, <span>купи</span>.</p>",
        footerSelected: "Филе из цыплят с трюфилями в бульоне.",
        footerDisabled: "Печалька, с курой закончился.",
    },
];